### Exercise 4
#### Prof. Flamm
#### Spring 2020

1. The first objective of this exercise is to load your state dataset into this Jupyter notebook. In part, this exercise is intended to assure you that you will be able to work with your state's data on your laptop, and not need to change states at the last minute.

2. Next, I would like you to estimate some summary statistics describing the distributions of wage and salary incomes in 1990 and 2000, by educational level, in your state. These include the mean, median, and variance of , as well as the deciles, of wage and salary income for each educational level in the workforce. We will use this exercise to work on visualizations of the data we will be using in our individual project analysis.

Your dataset contains a 5% public use sample of wage and salary-earning adults in US households from the 1990 and 2000 U.S. Census within your state. I'm going to do Idaho, since nobody else picked it and I like baked potatos.

In [1]:
import sys as sys
import numpy as np                  # pandas uses numpy, and sometimes want to use numpy within pandas
import pandas as pd                    # data package, redundant since already did
import matplotlib.pyplot as plt               # graphics package
import seaborn as sns               # makes matplotlib prettier without issuing a single command!
import datetime as dt                  # date and time module, often need to use

# check versions (overkill, but why not?)
print('Python version:', sys.version)
print('Pandas version: ', pd.__version__)

print(plt.style.available)
plt.style.use('fivethirtyeight')
%matplotlib inline

Python version: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Pandas version:  1.0.1
['bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn-bright', 'seaborn-colorblind', 'seaborn-dark-palette', 'seaborn-dark', 'seaborn-darkgrid', 'seaborn-deep', 'seaborn-muted', 'seaborn-notebook', 'seaborn-paper', 'seaborn-pastel', 'seaborn-poster', 'seaborn-talk', 'seaborn-ticks', 'seaborn-white', 'seaborn-whitegrid', 'seaborn', 'Solarize_Light2', 'tableau-colorblind10', '_classic_test']

#### 1. Please import your state's data set into this Jupyter notebook.

In [17]:
tstdf=pd.read_stata('state_files/Idaho.dta')
tstdf

,index,conspuma,stfip,stname,perwt,age,male,married,speakeng,empstat,...,locdt_noag,mex_t90,mex_dt,mex_t90_noag,mex_dt_noag,mex_rca,dchnmshare,border,ind,incwage
0,2945151,97,16,Idaho,32,44,1,1,1,1,...,-0.004051,0.000363,-0.000363,0.000000,0.000000,0.855161,0.023427,0,2,41999.996094
1,2945141,97,16,Idaho,18,53,1,1,1,1,...,-0.004051,0.000199,-0.000199,0.000199,-0.000199,0.018529,0.005507,0,49,41999.996094
2,2945142,97,16,Idaho,14,37,1,0,1,1,...,-0.004051,0.000363,-0.000363,0.000000,0.000000,0.855161,0.023427,0,2,340.000000
3,2945143,97,16,Idaho,15,38,0,0,1,1,...,-0.004051,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,202,1100.000122
4,2945144,97,16,Idaho,7,41,0,0,1,1,...,-0.004051,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,205,24999.992188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36101,2971226,102,16,Idaho,8,37,1,0,1,1,...,-0.013760,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,181,4799.998047
36102,2971225,102,16,Idaho,12,41,1,0,1,1,...,-0.013760,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,181,29999.990234
36103,2971224,102,16,Idaho,12,39,0,1,1,1,...,-0.013760,0.000000,0.000000,0.000000,0.000000,0.031609,0.000366,0,48,3199.998779
36104,2971199,102,16,Idaho,8,37,0,1,1,1,...,-0.013760,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,191,500.000061
36105,2971223,102,16,Idaho,12,39,1,1,1,1,...,-0.013760,0.000000,0.000000,0.000000,0.000000,0.031609,0.000366,0,48,14499.993164

In [18]:
tstdf.dtypes

index              int32
conspuma           int32
stfip              int32
stname            object
perwt              int16
age                 int8
male                int8
married             int8
speakeng            int8
empstat             int8
ind1990            int16
age2               int16
white               int8
yr                  int8
lhs                 int8
hs                  int8
scol                int8
col                 int8
logwage          float32
logwage_w        float32
locdchnmshare    float32
locvul           float32
locdt            float32
locvul_noag      float32
locdt_noag       float32
mex_t90          float64
mex_dt           float32
mex_t90_noag     float32
mex_dt_noag      float32
mex_rca          float32
dchnmshare       float32
border              int8
ind                int16
incwage          float32
dtype: object

In [20]:
tstdf.loc[tstdf.yr==0,'incwage'] # yr==0 is 1990, yr==1 is 2000

4512     18999.992188
4514     32999.988281
4515     24999.992188
4516     44069.003906
4517     18000.001953
             ...
36101     4799.998047
36102    29999.990234
36103     3199.998779
36104      500.000061
36105    14499.993164
Name: incwage, Length: 15183, dtype: float32

#### Mini-tutorial: we need to weight observations because Census uses a *stratified* sample
###### each observation represents a random draw from a subpopulation with different numbers of people in underlying population

Fortunately, `statsmodels` can handle this situation. It contains a package called `DescrStatsW` (not the most user friendly name in the world) that does descriptive statistics and tests with weights for case weights--which is what we have. You give it the weights, and a dataframe, and it creates a weighted statistics object with methods for various useful descriptive statistics.

In [21]:
from statsmodels.stats.weightstats import DescrStatsW as dsw 
#wtd_inc=dsw(tstdf.loc[:,'incwage'],weights=tstdf.loc[:,'perwt']) # person-weight variable, get incwage var only
wtd_df=dsw(tstdf,weights=tstdf.loc[:,'perwt']) # person-weight variable, use entire dataframe
# perwt is the weights variable
type(wtd_df)

statsmodels.stats.weightstats.DescrStatsW

[DescrStatsW documentation link](https://www.statsmodels.org/stable/generated/statsmodels.stats.weightstats.DescrStatsW.html)

In [22]:
# get person-weighted deciles of distribution of all variables in dataframe
wtd_df.quantile(np.arange(0,1.01,.1))

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col25,col26,col27,col28,col29,col30,col31,col32,col33,col34
p,,,,,,,,,,,,,,,,,,,,,
0.0,2939125,97,16,Idaho,1,25,0,0,0,1,...,-0.0185405,0,-0.0675981,0,-0.0675981,0,-0.0281843,0,1,3
0.1,2943600,97,16,Idaho,11,28,0,0,1,1,...,-0.0185405,0,-0.00689625,0,-0.000923014,0,0,0,12,6000
0.2,2947745,97,16,Idaho,18,31,0,0,1,1,...,-0.0137596,0,0,0,0,0,0,0,48,10400
0.3,2951781,98,16,Idaho,22,34,0,1,1,1,...,-0.0131742,0,0,0,0,0,0,0,90,14500
0.4,2955551,99,16,Idaho,24,37,0,1,1,1,...,-0.0131742,0,0,0,0,0,0,0,122,18000
0.5,2959455,100,16,Idaho,28,40,1,1,1,1,...,-0.0131742,0,0,0,0,0,0,0,150,22000
0.6,2963128,101,16,Idaho,29,43,1,1,1,1,...,-0.0126156,0,0,0,0,0,0,0,170,26000
0.7,2965740,101,16,Idaho,32,47,1,1,1,1,...,-0.0117687,0,0,0,0,0,0,0,201,31000
0.8,2968330,101,16,Idaho,36,51,1,1,1,1,...,-0.0040505,0,0,0,0,0.0343306,0.00340579,0,205,38000
0.9,2971570,102,16,Idaho,40,55,1,1,1,1,...,-0.0040505,0.00689625,0,0.00103905,0,0.407885,0.0259505,0,219,50000
1.0,2975230,102,16,Idaho,126,64,1,1,1,1,...,-0.0040505,0.0866215,0.0012388,0.0866214,0.0012388,21.7705,0.466414,0,238,302000

In [23]:
df_qntls=wtd_df.quantile(np.arange(0,1.01,.1))
print(type(df_qntls)) # quantile method creates a dataframe
df_qntls.columns=tstdf.columns # rename columns to meaningful variable names
df_qntls

<class 'pandas.core.frame.DataFrame'>

,index,conspuma,stfip,stname,perwt,age,male,married,speakeng,empstat,...,locdt_noag,mex_t90,mex_dt,mex_t90_noag,mex_dt_noag,mex_rca,dchnmshare,border,ind,incwage
p,,,,,,,,,,,,,,,,,,,,,
0.0,2939125,97,16,Idaho,1,25,0,0,0,1,...,-0.0185405,0,-0.0675981,0,-0.0675981,0,-0.0281843,0,1,3
0.1,2943600,97,16,Idaho,11,28,0,0,1,1,...,-0.0185405,0,-0.00689625,0,-0.000923014,0,0,0,12,6000
0.2,2947745,97,16,Idaho,18,31,0,0,1,1,...,-0.0137596,0,0,0,0,0,0,0,48,10400
0.3,2951781,98,16,Idaho,22,34,0,1,1,1,...,-0.0131742,0,0,0,0,0,0,0,90,14500
0.4,2955551,99,16,Idaho,24,37,0,1,1,1,...,-0.0131742,0,0,0,0,0,0,0,122,18000
0.5,2959455,100,16,Idaho,28,40,1,1,1,1,...,-0.0131742,0,0,0,0,0,0,0,150,22000
0.6,2963128,101,16,Idaho,29,43,1,1,1,1,...,-0.0126156,0,0,0,0,0,0,0,170,26000
0.7,2965740,101,16,Idaho,32,47,1,1,1,1,...,-0.0117687,0,0,0,0,0,0,0,201,31000
0.8,2968330,101,16,Idaho,36,51,1,1,1,1,...,-0.0040505,0,0,0,0,0.0343306,0.00340579,0,205,38000
0.9,2971570,102,16,Idaho,40,55,1,1,1,1,...,-0.0040505,0.00689625,0,0.00103905,0,0.407885,0.0259505,0,219,50000
1.0,2975230,102,16,Idaho,126,64,1,1,1,1,...,-0.0040505,0.0866215,0.0012388,0.0866214,0.0012388,21.7705,0.466414,0,238,302000

* 0 quantile = minimum (not affected by weighting)
* 1 quantile = maximum (not affected by weighting)
* .5 quantile = median (affected by weighting)

In [24]:
tstdf.mex_dt_noag.describe() # describe unweighted variable

count    36106.000000
mean        -0.001874
std          0.009065
min         -0.067598
25%          0.000000
50%          0.000000
75%          0.000000
max          0.001239
Name: mex_dt_noag, dtype: float64

* How you can extract interesting [unweighted] quantile values as constants with pandas quantiles method:

In [57]:
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=tstdf['incwage'].quantile(np.arange(0,1.01,.1))
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)

3.0 5998.4990234375 10000.0009765625 14000.005859375 17665.00390625 21000.009765625 24999.9921875 29999.990234375 36999.9921875 49000.01171875 301999.96875

* same trick can be made to work with statsmodels weighted quantiles:

In [25]:
wtd_incwage=dsw(tstdf.loc[:,'incwage'],weights=tstdf.loc[:,'perwt']) # person-weight variable
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=wtd_incwage.quantile(np.arange(0,1.01,.1))
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)
type(wtd_incwage)

3.0 5999.998046875 10400.001953125 14499.9931640625 18000.001953125 21999.9921875 25999.994140625 31000.001953125 38000.00390625 50000.0078125 301999.96875

statsmodels.stats.weightstats.DescrStatsW

* basic weighted descriptive statistics are available as *properties* of DescrStatsW object

In [26]:
print(wtd_incwage.mean,wtd_incwage.var,wtd_incwage.sum,wtd_incwage.sum_weights,wtd_incwage.nobs)

27251.013533493497 709705424.0130329 20285027701.02129 744377.0 744377.0

* but weighted quantiles are a DescrStatsW *method*

In [27]:
wtd_incwage.quantile(np.arange(0,1.01,.1))

p
0.0         3.000000
0.1      5999.998047
0.2     10400.001953
0.3     14499.993164
0.4     18000.001953
0.5     21999.992188
0.6     25999.994141
0.7     31000.001953
0.8     38000.003906
0.9     50000.007812
1.0    301999.968750
dtype: float64

In [28]:
tstdf.incwage.describe() # unweighted distribution, min and max match but not median

count     36106.000000
mean      26110.537109
std       25013.210938
min           3.000000
25%       12000.000977
50%       21000.009766
75%       32999.988281
max      301999.968750
Name: incwage, dtype: float64

In [29]:
#compare to unweighted quantiles
tstdf.loc[:,'incwage'].quantile(np.arange(0,1.01,.1))

0.0         3.000000
0.1      5998.499023
0.2     10000.000977
0.3     14000.005859
0.4     17665.003906
0.5     21000.009766
0.6     24999.992188
0.7     29999.990234
0.8     36999.992188
0.9     49000.011719
1.0    301999.968750
Name: incwage, dtype: float64

> Actually, fairly close!

#### 2. Now, divide your state into 8 separate dataframes based on educational group and year (1990-yr==0, vs. 2000-yr==1):

#### 3. Now, report the following basic weighted descriptive statistics for each educational group/yr's `incwage`:
##### mean, median, variance

#### 4. Now report the weighted deciles of `incwage` for each educational group and year within your state:

#### 5. Now, please prepare a bar graph(s) contrasting the deciles of incwage for each of the educational groups within your state in 1990:

#### 5. Now, please prepare a bar graph(s) contrasting the deciles of incwage for each of the educational groups within your state in 2000: