### Exercise 4
#### Prof. Flamm
#### Spring 2020

1. The first objective of this exercise is to load your state dataset into this Jupyter notebook. In part, this exercise is intended to assure you that you will be able to work with your state's data on your laptop, and not need to change states at the last minute.

2. Next, I would like you to estimate some summary statistics describing the distributions of wage and salary incomes in 1990 and 2000, by educational level, in your state. These include the mean, median, and variance of , as well as the deciles, of wage and salary income for each educational level in the workforce. We will use this exercise to work on visualizations of the data we will be using in our individual project analysis.

Your dataset contains a 5% public use sample of wage and salary-earning adults in US households from the 1990 and 2000 U.S. Census within your state. I'm going to do Idaho, since nobody else picked it and I like baked potatos.

In [1]:
import sys as sys
import numpy as np                  # pandas uses numpy, and sometimes want to use numpy within pandas
import pandas as pd                    # data package, redundant since already did
import matplotlib.pyplot as plt               # graphics package
import seaborn as sns               # makes matplotlib prettier without issuing a single command!
import datetime as dt                  # date and time module, often need to use

# check versions (overkill, but why not?)
print('Python version:', sys.version)
print('Pandas version: ', pd.__version__)

print(plt.style.available)
plt.style.use('fivethirtyeight')
%matplotlib inline

Python version: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Pandas version:  1.0.1
['bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn-bright', 'seaborn-colorblind', 'seaborn-dark-palette', 'seaborn-dark', 'seaborn-darkgrid', 'seaborn-deep', 'seaborn-muted', 'seaborn-notebook', 'seaborn-paper', 'seaborn-pastel', 'seaborn-poster', 'seaborn-talk', 'seaborn-ticks', 'seaborn-white', 'seaborn-whitegrid', 'seaborn', 'Solarize_Light2', 'tableau-colorblind10', '_classic_test']

#### 1. Please import your state's data set into this Jupyter notebook.

In [2]:
pd.set_option("display.max_columns", 101)

df=pd.read_stata('Pennsylvania.dta')
df

,index,conspuma,stfip,stname,perwt,age,male,married,speakeng,empstat,ind1990,age2,white,yr,lhs,hs,scol,col,logwage,logwage_w,locdchnmshare,locvul,locdt,locvul_noag,locdt_noag,mex_t90,mex_dt,mex_t90_noag,mex_dt_noag,mex_rca,dchnmshare,border,ind,incwage
0,7365502,391,42,Pennsylvania,14,53,0,0,1,1,591,2809,1,1,0,1,0,0,9.510445,5.559201,0.016261,0.008693,-0.008106,0.008368,-0.007788,0.0,0.0,0.0,0.0,0.0,0.0,0,133,13499.996094
1,7365503,391,42,Pennsylvania,43,27,0,0,1,1,862,729,1,1,0,1,0,0,9.457200,5.585999,0.016261,0.008693,-0.008106,0.008368,-0.007788,0.0,0.0,0.0,0.0,0.0,0.0,0,211,12799.995117
2,7365500,391,42,Pennsylvania,14,52,1,1,1,1,702,2704,1,1,0,0,0,1,10.085809,6.134565,0.016261,0.008693,-0.008106,0.008368,-0.007788,0.0,0.0,0.0,0.0,0.0,0.0,0,167,23999.992188
3,7365501,391,42,Pennsylvania,18,51,0,1,1,1,842,2601,1,1,0,0,0,1,10.858999,7.195437,0.016261,0.008693,-0.008106,0.008368,-0.007788,0.0,0.0,0.0,0.0,0.0,0.0,0,205,52000.011719
4,7365499,391,42,Pennsylvania,21,47,0,1,1,1,922,2209,1,1,0,1,0,0,9.746834,5.795590,0.016261,0.008693,-0.008106,0.008368,-0.007788,0.0,0.0,0.0,0.0,0.0,0.0,0,228,17100.001953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418968,7778249,422,42,Pennsylvania,7,40,0,0,1,1,641,1600,1,0,1,0,0,0,9.210340,5.952244,0.010533,0.009782,-0.007547,0.009131,-0.006908,0.0,0.0,0.0,0.0,0.0,0.0,0,150,10000.000977
418969,7778248,422,42,Pennsylvania,7,57,1,1,1,1,831,3249,1,0,0,0,0,1,10.558414,8.073507,0.010533,0.009782,-0.007547,0.009131,-0.006908,0.0,0.0,0.0,0.0,0.0,0.0,0,201,38500.000000
418970,7778254,422,42,Pennsylvania,8,28,1,1,1,1,601,784,1,0,0,1,0,0,9.903487,6.437752,0.010533,0.009782,-0.007547,0.009131,-0.006908,0.0,0.0,0.0,0.0,0.0,0.0,0,136,19999.992188
418971,7778247,422,42,Pennsylvania,7,34,1,1,1,1,450,1156,1,0,0,1,0,0,10.012341,6.428823,0.010533,0.009782,-0.007547,0.009131,-0.006908,0.0,0.0,0.0,0.0,0.0,0.0,0,103,22299.990234
418972,7778246,422,42,Pennsylvania,8,28,1,1,1,1,621,784,1,0,0,1,0,0,9.615806,5.664562,0.010533,0.009782,-0.007547,0.009131,-0.006908,0.0,0.0,0.0,0.0,0.0,0.0,0,142,15000.001953

In [8]:
df.dtypes

index              int32
conspuma           int32
stfip              int32
stname            object
perwt              int16
age                 int8
male                int8
married             int8
speakeng            int8
empstat             int8
ind1990            int16
age2               int16
white               int8
yr                  int8
lhs                 int8
hs                  int8
scol                int8
col                 int8
logwage          float32
logwage_w        float32
locdchnmshare    float32
locvul           float32
locdt            float32
locvul_noag      float32
locdt_noag       float32
mex_t90          float64
mex_dt           float32
mex_t90_noag     float32
mex_dt_noag      float32
mex_rca          float32
dchnmshare       float32
border              int8
ind                int16
incwage          float32
dtype: object

In [3]:
df.loc[df.yr==0,'incwage'] # yr==0 is 1990, yr==1 is 2000

1369      22999.992188
1371       8600.002930
1372      17117.001953
1373      13000.002930
1374       5782.999512
              ...
418968    10000.000977
418969    38500.000000
418970    19999.992188
418971    22299.990234
418972    15000.001953
Name: incwage, Length: 201940, dtype: float32

#### Mini-tutorial: we need to weight observations because Census uses a *stratified* sample
###### each observation represents a random draw from a subpopulation with different numbers of people in underlying population

Fortunately, `statsmodels` can handle this situation. It contains a package called `DescrStatsW` (not the most user friendly name in the world) that does descriptive statistics and tests with weights for case weights--which is what we have. You give it the weights, and a dataframe, and it creates a weighted statistics object with methods for various useful descriptive statistics.

In [4]:
from statsmodels.stats.weightstats import DescrStatsW as dsw 
#wtd_inc=dsw(df.loc[:,'incwage'],weights=df.loc[:,'perwt']) # person-weight variable, get incwage var only
wtd_df=dsw(df,weights=df.loc[:,'perwt']) # person-weight variable, use entire dataframe
# perwt is the weights variable
type(wtd_df)

statsmodels.stats.weightstats.DescrStatsW

[DescrStatsW documentation link](https://www.statsmodels.org/stable/generated/statsmodels.stats.weightstats.DescrStatsW.html)

In [5]:
# get person-weighted deciles of distribution of all variables in dataframe
wtd_df.quantile(np.arange(0,1.01,.1))

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15,col16,col17,col18,col19,col20,col21,col22,col23,col24,col25,col26,col27,col28,col29,col30,col31,col32,col33,col34
p,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0.0,7363676,391,42,Pennsylvania,1,25,0,0,0,1,10,625,0,0,0,0,0,0,0,-3.95124,0.00705733,0.00630161,-0.0250605,0.00596069,-0.0235241,0,-0.0675981,0,-0.0675981,0,-0.0281843,0,1,1
0.1,7421702,398,42,Pennsylvania,11,28,0,0,1,1,151,784,0,0,0,0,0,0,8.96954,5.23644,0.00750073,0.0100905,-0.016196,0.00914998,-0.0148885,0,-0.00190116,0,-0.00138946,0,0,0,28,7860
0.2,7460933,400,42,Pennsylvania,18,31,0,0,1,1,300,961,1,0,0,0,0,0,9.46498,5.62682,0.00759415,0.0100905,-0.0142045,0.00977386,-0.0122998,0,0,0,0,0,0,0,67,12900
0.3,7500629,404,42,Pennsylvania,21,35,0,0,1,1,410,1225,1,0,0,0,0,0,9.74097,5.86977,0.00950243,0.0109897,-0.0134721,0.0104094,-0.0121712,0,0,0,0,0,0,0,93,17000
0.4,7540222,407,42,Pennsylvania,25,38,0,1,1,1,580,1444,1,0,0,0,0,0,9.95228,6.04755,0.0120655,0.0126641,-0.0129257,0.0109377,-0.0111343,0,0,0,0,0,0,0,129,21000
0.5,7590651,409,42,Pennsylvania,25,41,1,1,1,1,641,1681,1,1,0,0,0,0,10.1266,6.21845,0.0130158,0.0134358,-0.0109886,0.0124252,-0.01062,0,0,0,0,0,0,0,150,25000
0.6,7624095,410,42,Pennsylvania,29,44,1,1,1,1,721,1936,1,1,0,1,0,0,10.309,6.3905,0.0132238,0.0141581,-0.0108546,0.0128775,-0.00958086,0,0,0,0,0,0,0,171,30000
0.7,7659090,412,42,Pennsylvania,32,47,1,1,1,1,831,2209,1,1,0,1,0,0,10.4631,6.56244,0.0150635,0.0150268,-0.00997729,0.0138335,-0.00939771,0,0,0,0,0,0,0,201,35000
0.8,7694751,414,42,Pennsylvania,35,51,1,1,1,1,842,2601,1,1,0,1,1,1,10.6454,6.76317,0.0150635,0.0168244,-0.00927504,0.0143848,-0.00896402,0,0,0,0,0.0531534,0.000767912,0,205,42000
0.9,7731718,416,42,Pennsylvania,40,56,1,1,1,1,870,3136,1,1,0,1,1,1,10.9331,7.05086,0.018585,0.017784,-0.00837939,0.0164531,-0.00774538,0.00198868,0,0.00138946,0,0.255404,0.0399524,0,213,56000
1.0,7782648,422,42,Pennsylvania,176,64,1,1,1,1,960,4096,1,1,1,1,1,1,12.6443,11.2252,0.0242659,0.0272632,-0.00568048,0.0256992,-0.00534561,0.0866215,0.0012388,0.0866214,0.0012388,21.7705,0.466414,0,238,310000

In [23]:
df_qntls=wtd_df.quantile(np.arange(0,1.01,.1))
print(type(df_qntls)) # quantile method creates a dataframe
df_qntls.columns=df.columns # rename columns to meaningful variable names
df_qntls

<class 'pandas.core.frame.DataFrame'>

,index,conspuma,stfip,stname,perwt,age,male,married,speakeng,empstat,...,locdt_noag,mex_t90,mex_dt,mex_t90_noag,mex_dt_noag,mex_rca,dchnmshare,border,ind,incwage
p,,,,,,,,,,,,,,,,,,,,,
0.0,2939125,97,16,Idaho,1,25,0,0,0,1,...,-0.0185405,0,-0.0675981,0,-0.0675981,0,-0.0281843,0,1,3
0.1,2943600,97,16,Idaho,11,28,0,0,1,1,...,-0.0185405,0,-0.00689625,0,-0.000923014,0,0,0,12,6000
0.2,2947745,97,16,Idaho,18,31,0,0,1,1,...,-0.0137596,0,0,0,0,0,0,0,48,10400
0.3,2951781,98,16,Idaho,22,34,0,1,1,1,...,-0.0131742,0,0,0,0,0,0,0,90,14500
0.4,2955551,99,16,Idaho,24,37,0,1,1,1,...,-0.0131742,0,0,0,0,0,0,0,122,18000
0.5,2959455,100,16,Idaho,28,40,1,1,1,1,...,-0.0131742,0,0,0,0,0,0,0,150,22000
0.6,2963128,101,16,Idaho,29,43,1,1,1,1,...,-0.0126156,0,0,0,0,0,0,0,170,26000
0.7,2965740,101,16,Idaho,32,47,1,1,1,1,...,-0.0117687,0,0,0,0,0,0,0,201,31000
0.8,2968330,101,16,Idaho,36,51,1,1,1,1,...,-0.0040505,0,0,0,0,0.0343306,0.00340579,0,205,38000
0.9,2971570,102,16,Idaho,40,55,1,1,1,1,...,-0.0040505,0.00689625,0,0.00103905,0,0.407885,0.0259505,0,219,50000
1.0,2975230,102,16,Idaho,126,64,1,1,1,1,...,-0.0040505,0.0866215,0.0012388,0.0866214,0.0012388,21.7705,0.466414,0,238,302000

* 0 quantile = minimum (not affected by weighting)
* 1 quantile = maximum (not affected by weighting)
* .5 quantile = median (affected by weighting)

In [6]:
df.mex_dt_noag.describe() # describe unweighted variable

count    418973.000000
mean         -0.001675
std           0.006545
min          -0.067598
25%           0.000000
50%           0.000000
75%           0.000000
max           0.001239
Name: mex_dt_noag, dtype: float64

* How you can extract interesting [unweighted] quantile values as constants with pandas quantiles method:

In [7]:
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=df['incwage'].quantile(np.arange(0,1.01,.1))
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)

1.0 7499.99755859375 12000.0009765625 16600.005859375 19999.9921875 24699.9921875 29000.0 33999.98828125 40600.01171875 53999.984375 309999.875

* same trick can be made to work with statsmodels weighted quantiles:

In [8]:
wtd_incwage=dsw(df.loc[:,'incwage'],weights=df.loc[:,'perwt']) # person-weight variable
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=wtd_incwage.quantile(np.arange(0,1.01,.1))
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)
type(wtd_incwage)

1.0 7859.99755859375 12900.0048828125 17000.001953125 21000.009765625 24999.9921875 29999.990234375 35000.0 41999.99609375 56000.0234375 309999.875

statsmodels.stats.weightstats.DescrStatsW

* basic weighted descriptive statistics are available as *properties* of DescrStatsW object

In [9]:
print(wtd_incwage.mean,wtd_incwage.var,wtd_incwage.sum,wtd_incwage.sum_weights,wtd_incwage.nobs)

31491.87738320733 990626545.035259 264701227811.14062 8405381.0 8405381.0

* but weighted quantiles are a DescrStatsW *method*

In [10]:
wtd_incwage.quantile(np.arange(0,1.01,.1))

p
0.0         1.000000
0.1      7859.997559
0.2     12900.004883
0.3     17000.001953
0.4     21000.009766
0.5     24999.992188
0.6     29999.990234
0.7     35000.000000
0.8     41999.996094
0.9     56000.023438
1.0    309999.875000
dtype: float64

In [11]:
df.incwage.describe() # unweighted distribution, min and max match but not median

count    418973.000000
mean      30241.406250
std       29953.597656
min           1.000000
25%       14800.002930
50%       24699.992188
75%       36999.992188
max      309999.875000
Name: incwage, dtype: float64

In [12]:
#compare to unweighted quantiles
df.loc[:,'incwage'].quantile(np.arange(0,1.01,.1))

0.0         1.000000
0.1      7499.997559
0.2     12000.000977
0.3     16600.005859
0.4     19999.992188
0.5     24699.992188
0.6     29000.000000
0.7     33999.988281
0.8     40600.011719
0.9     53999.984375
1.0    309999.875000
Name: incwage, dtype: float64

> Actually, fairly close!

#### 2. Now, divide your state into 8 separate dataframes based on educational group and year (1990-yr==0, vs. 2000-yr==1):

In [55]:
pd.set_option("display.max_columns", 101)
wtd_incwage=dsw(df.loc[:,'incwage'],weights=df.loc[:,'perwt']) # person-weight variable
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=wtd_incwage.quantile(np.arange(0,1.01,.1))
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)

less_hs1990 = df.loc[((df['lhs'] == 1) & (df['yr'] == 0))]
less_hs2000 = df.loc[((df['lhs'] == 1) & (df['yr'] == 1))]
hs1990 = df.loc[((df['hs'] == 1) & (df['yr'] == 0))]
hs2000 = df.loc[((df['hs'] == 1) & (df['yr'] == 1))]
some_college1990 = df.loc[((df['scol'] == 1) & (df['yr'] == 0))]
some_college2000 = df.loc[((df['scol'] == 1) & (df['yr'] == 1))]
college1990 = df.loc[((df['col'] == 1) & (df['yr'] == 0))]
college2000 = df.loc[((df['col'] == 1) & (df['yr'] == 1))]

1.0 7859.99755859375 12900.0048828125 17000.001953125 21000.009765625 24999.9921875 29999.990234375 35000.0 41999.99609375 56000.0234375 309999.875

#### 3. Now, report the following basic weighted descriptive statistics for each educational group/yr's `incwage`:
##### mean, median, variance

In [51]:
pd.options.display.float_format = '{:,.2f}'.format

wtd_incwage_lhs90 =dsw(less_hs1990.loc[:,'incwage'],weights=less_hs1990.loc[:,'perwt']) # person-weight variable
print("Less than High school (1990)")
print("Mean:",wtd_incwage_lhs90.mean,"Median:", wtd_incwage_lhs90.quantile(.5), "Variance:",wtd_incwage_lhs90.var)

print("")

wtd_incwage_lhs00 =dsw(less_hs2000.loc[:,'incwage'],weights=less_hs2000.loc[:,'perwt']) # person-weight variable
print("Less than High school (2000)")
print("Mean:",wtd_incwage_lhs00.mean,"Median:",wtd_incwage_lhs00.quantile(.5), "Variance:",wtd_incwage_lhs00.var)

print("")

wtd_incwage_hs90 =dsw(hs1990.loc[:,'incwage'],weights=hs1990.loc[:,'perwt']) # person-weight variable
print("High school (1990)")
print("Mean:",wtd_incwage_hs90.mean,"Median:",wtd_incwage_hs90.quantile(.5), "Variance:",wtd_incwage_hs90.var)

print("")

wtd_incwage_hs00 =dsw(hs2000.loc[:,'incwage'],weights=hs2000.loc[:,'perwt']) # person-weight variable
print("High school (2000)")
print("Mean:",wtd_incwage_hs00.mean,"Median:",wtd_incwage_hs00.quantile(.5), "Variance:",wtd_incwage_hs00.var)

print("")

wtd_incwage_scol90 =dsw(some_college1990.loc[:,'incwage'],weights=some_college1990.loc[:,'perwt']) # person-weight variable
print("Some College (1990)")
print("Mean:",wtd_incwage_scol90.mean,"Median:",wtd_incwage_scol90.quantile(.5), "Variance:",wtd_incwage_scol90.var)

print("")

wtd_incwage_scol00 =dsw(some_college2000.loc[:,'incwage'],weights=some_college2000.loc[:,'perwt']) # person-weight variable
print("Some College (2000)")
print("Mean:",wtd_incwage_scol00.mean,"Median:",wtd_incwage_scol00.quantile(.5), "Variance:",wtd_incwage_scol00.var)

print("")

wtd_incwage_col90 =dsw(college1990.loc[:,'incwage'],weights=college1990.loc[:,'perwt']) # person-weight variable
print("College (1990)")
print("Mean:",wtd_incwage_col90.mean,"Median:",wtd_incwage_col90.quantile(.5), "Variance:",wtd_incwage_col90.var)

print("")

wtd_incwage_col00 =dsw(college2000.loc[:,'incwage'],weights=college2000.loc[:,'perwt']) # person-weight variable
print("College (2000)")
print("Mean:",wtd_incwage_col00.mean,"Median:",wtd_incwage_col00.quantile(.5), "Variance:",wtd_incwage_col00.var)

Less than High school (1990)
Mean: 18270.16166218154 Median: p
0.50   15,999.99
dtype: float64 Variance: 206967825.97012058

Less than High school (2000)
Mean: 23627.99677508502 Median: p
0.50   19,999.99
dtype: float64 Variance: 588169766.1355953

High school (1990)
Mean: 20267.502330341536 Median: p
0.50   18,000.00
dtype: float64 Variance: 214929796.62233704

High school (2000)
Mean: 27748.458350356916 Median: p
0.50   24,999.99
dtype: float64 Variance: 465739076.741421

Some College (1990)
Mean: 24847.86218996005 Median: p
0.50   21,999.99
dtype: float64 Variance: 352438252.56811154

Some College (2000)
Mean: 33560.72703217617 Median: p
0.50   29,999.99
dtype: float64 Variance: 711917468.727108

College (1990)
Mean: 37393.026539097475 Median: p
0.50   30,318.99
dtype: float64 Variance: 1000009267.3281235

College (2000)
Mean: 55264.60916268397 Median: p
0.50   43,000.02
dtype: float64 Variance: 2851739368.231364

#### 4. Now report the weighted deciles of `incwage` for each educational group and year within your state:

In [54]:
pd.options.display.float_format = '{:,.2f}'.format


wtd_incwage_lhs90 =dsw(less_hs1990.loc[:,'incwage'],weights=less_hs1990.loc[:,'perwt']) # person-weight variable
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=wtd_incwage_lhs90.quantile(np.arange(0,1.01,.1))
print("Less than High school (1990)")
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)

print("")

wtd_incwage_lhs00 =dsw(less_hs2000.loc[:,'incwage'],weights=less_hs2000.loc[:,'perwt']) # person-weight variable
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=wtd_incwage_hs90.quantile(np.arange(0,1.01,.1))
print("Less than High school (2000)")
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)

print("")

wtd_incwage_hs90 =dsw(hs1990.loc[:,'incwage'],weights=hs1990.loc[:,'perwt']) # person-weight variable
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=wtd_incwage_hs90.quantile(np.arange(0,1.01,.1))
print("High school (1990)")
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)


print("")

wtd_incwage_hs00 =dsw(hs2000.loc[:,'incwage'],weights=hs2000.loc[:,'perwt']) # person-weight variable
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=wtd_incwage_hs00.quantile(np.arange(0,1.01,.1))
print("High school (2000)")
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)


print("")

wtd_incwage_scol90 =dsw(some_college1990.loc[:,'incwage'],weights=some_college1990.loc[:,'perwt']) # person-weight variable
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=wtd_incwage_scol90.quantile(np.arange(0,1.01,.1))
print("Some College (1990)")
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)


print("")

wtd_incwage_scol00 =dsw(some_college2000.loc[:,'incwage'],weights=some_college2000.loc[:,'perwt']) # person-weight variable
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=wtd_incwage_scol00.quantile(np.arange(0,1.01,.1))
print("Some College (2000)")
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)


print("")

wtd_incwage_col90 =dsw(college1990.loc[:,'incwage'],weights=college1990.loc[:,'perwt']) # person-weight variable
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=wtd_incwage_col90.quantile(np.arange(0,1.01,.1))
print("College (1990)")
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)


print("")

wtd_incwage_col00 =dsw(college2000.loc[:,'incwage'],weights=college2000.loc[:,'perwt']) # person-weight variable
dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax=wtd_incwage_col00.quantile(np.arange(0,1.01,.1))
print("College (2000)")
print(dmin,d1,d2,d3,d4,d5,d6,d7,d8,d9,dmax)

Less than High school (1990)
2.0 4999.998046875 8000.0009765625 10478.0029296875 13000.0029296875 15999.994140625 18999.9921875 21999.9921875 26500.0078125 32999.98828125 194742.015625

Less than High school (2000)
1.0 5499.998046875 9416.99609375 12295.0048828125 15099.998046875 18000.001953125 21000.009765625 24999.9921875 29750.01171875 35925.015625 194742.015625

High school (1990)
1.0 5499.998046875 9416.99609375 12295.0048828125 15099.998046875 18000.001953125 21000.009765625 24999.9921875 29750.01171875 35925.015625 194742.015625

High school (2000)
4.0 8100.0009765625 13000.0029296875 17300.00390625 21000.009765625 24999.9921875 29000.0 32999.98828125 39700.00390625 49000.01171875 309999.875

Some College (1990)
10.0 6999.99951171875 12000.0009765625 15800.005859375 18999.9921875 21999.9921875 24999.9921875 29999.990234375 34499.98828125 41999.99609375 194742.015625

Some College (2000)
4.0 10000.0009765625 16600.005859375 21000.009765625 24999.9921875 29999.990234375 33999.98828125 40000.00390625 46000.00390625 57000.00390625 309999.875

College (1990)
6.999999523162842 10000.0009765625 17125.001953125 22210.99609375 26965.0078125 30318.990234375 35000.0 40249.99609375 50000.0078125 65000.01953125 194742.015625

College (2000)
30.000001907348633 15000.001953125 23999.9921875 29999.990234375 36999.9921875 43000.015625 50000.0078125 58999.984375 70000.03125 97999.9765625 309999.875

#### 5. Now, please prepare a bar graph(s) contrasting the deciles of incwage for each of the educational groups within your state in 1990:

#### 5. Now, please prepare a bar graph(s) contrasting the deciles of incwage for each of the educational groups within your state in 2000: